FROM openjdk:8
ADD target/MicroservSpringBootAssignment-0.0.1-SNAPSHOT.jar MicroservSpringBootAssignment-0.0.1-SNAPSHOT.jar
EXPOSE 8086
ENTRYPOINT ["java", "-jar", "MicroservSpringBootAssignment-0.0.1-SNAPSHOT.jar"]
